contain_min_version: 1.0.0
images:
  - image: aegir.lan:5000/singularo/singularo-dev:20260208-3
    name: singularo-dev
    dockerfile: Dockerfile
    default_shell: /bin/bash
    var:
      - name: WORKDIR_PATH
        command: git rev-parse --show-toplevel
    env:
      - CLAUDE_CONFIG_DIR=/claude
      - COLORTERM=truecolor
    mounts:
      - src: "$HOME/.claude-contain"
        dst: "/claude"
        type: "bind"
      - src: "$HOME/.codex"
        dst: "/home/$USER/.codex"
        type: "bind"
    ports:
      - 1455:1455         # codex
    flags:
      - i
    commands:
      - any
